### ISSUE TITLE
[FEEDBACK] Thanks a million times.

### ISSUE THREAD

**Issue by onegex1214** [ArtVentureX/sd-webui-agent-scheduler#1]
It was mind boggling for me to try and wrap my head around this thought:

Why the hell isn't there a queue function yet ????????????

Been waiting since November for something like this eagerly ! But I'm limited by my knowledge of code. I did try so many times with GPT, but failed miserably. And here you arrive like an angel. With this freaking awesomely built queue feature. 

Thank you so damn much. 
Very deeply appreciated. 
Love.

**Comment by onegex1214** [comment]
@artventurdev Is there by anychance a shortcut to add to queue ?

**Comment by artventurdev** [comment]
Hi @onegex1214, thank you so much for your kind words. I'm glad that you find this extension useful.

Our team has also been looking for such a feature for some time and decided to build our own solution.

> Is there by anychance a shortcut to add to queue ?

Can you describe a bit more. So you would like to have the queue button some where else?

**Comment by onegex1214** [comment]
@artventurdev No I meant, for instance to quickly launch a gen on webui its ctrl+enter. What's the shortcut if there is one to send to queue ?

**Comment by artventurdev** [comment]
@onegex1214 Ohh got you, nice feature. Added to my backlog.

**Comment by artventurdev** [comment]
I have created a seperated issue for better management: #8

**Comment by artventuredev** [comment]
@onegex1214 It's a bit late but this feature is implemented on the latest update. You can also change the shortcut in settings.

**Comment by DrJKL** [comment]
Could you add Enter/Return to the allowed keys? Right now hitting the shortcut in the prompt field adds the character to the prompt.

**Comment by artventuredev** [comment]
@DrJKL I fixed the redundant character issue, and also added the `Enter` key ;)
