### ISSUE TITLE
multiple-user change checkpoint wrong

### ISSUE THREAD

**Issue by zrjisme** [ArtVentureX/sd-webui-agent-scheduler#100]
When modifying a checkpoint in a multi-user environment, if User A submits Task Model 1 and User B submits Task Model 2, when User A submits another task, the task model will automatically be changed to Model 2. However, the user interface still displays Model 1. Is it possible to modify it so that the task is submitted based on the current page settings? or anyway to solve this problem？

**Comment by artventuredev** [comment]
Thanks for an interesting request. Please try the latest version to see if this issue is resolved.

**Comment by zrjisme** [comment]
Thank you for your response. I was able to use it correctly after updating the version. Thank you very much for your help. It saved me half a month's time. Thank you.
