### ISSUE TITLE
Warning: script controlnet is not in script_runner.alwayson_scripts

### ISSUE THREAD

**Issue by JohnnyStreet** [ArtVentureX/sd-webui-agent-scheduler#102]
I can't seem to get any scripts to work in sd-webui-agent-scheduler using the same alwayson_scripts settings I use directly with the API.

**Comment by artventuredev** [comment]
Please update to the latest version if you can - the issue you're facing (similar to #91) has been rectified there. Hope this helps!

**Comment by JohnnyStreet** [comment]
@artventuredev updating did not solve it but I was able to get it working using "ControlNet" instead of "controlnet". I am still trying to figure out the formatting for other scripts, for example "face editor ex".

**Comment by artventuredev** [comment]
Hmm my bad, both upper and lower script title should be allowed. For now, you need to enter the correct casing. I'll make a fix for this soon.

To get the correct script name you need to read the code of the extension, it's the `title` of the `Script` class. In your case it's `Face Editor EX`. But please note that even with the next update, the allowed value can be `face editor ex`, `Face Editor EX` or `face Editor ex`, but NOT `FaceEditorEx`.

See https://github.com/ototadana/sd-face-editor/blob/f945fc7dadad991486cf6cbc33fb8f089404e21c/scripts/face_editor_extension.py#L15

**Comment by JohnnyStreet** [comment]
> the allowed values can be `face editor ex`, `Face Editor EX`, or `face Editor ex`, but NOT `FaceEditorEx`

I am pretty sure I tried all of these. I have always used "face editor ex" outside of agent scheduler. It really needs to allow the same settings to be passed as they would directly to the API because there are lots of existing examples that show them in lowercase. I know it's tedious to fix but imagine how we feel having to guess or look up each extension name in their code to make sure we didn't type Ex instead of EX or something. I appreciate you taking the time to address it.

**Comment by artventuredev** [comment]
@JohnnyStreet The issue should be fixed in the latest update, please give it a try.

**Comment by JohnnyStreet** [comment]
@artventuredev Fantastic, thank you so much!

**Comment by artventuredev** [comment]
@JohnnyStreet There was a mistake in the previous commit, so please update one more time.

**Comment by chestnutpcj** [comment]
> @artventuredev太棒了，非常感谢！

Can it be used correctly now?When I use  alwayson_scripts: { controlnet: {args: [ { enabled: true, image: base64}]}} will report an error “string indices must be integers”？

**Comment by artventuredev** [comment]
Here's a working example with `ControlNet`:

```
{
  "prompt": "1girl",
  "negative_prompt": "EasyNegative",
  "alwayson_scripts": {
    "controlnet": {
      "args": [
        {
          "enabled": true,
          "image": {
            "image": "https://d2lae7oxvyyfdd.cloudfront.net/poses/5609.jpeg"
          },
          "model": "control_v11p_sd15_openpose [cab727d4]"
        }
      ]
    }
  }
}
```

The `image` field should be a `Dict` with `"image"` and an optional `"mask"`. You can use URL or base64 for image and mask.
