### ISSUE TITLE
Generation halts if queue has pending items, when switching to Agent Scheduler tab

### ISSUE THREAD

**Issue by zethriller** [ArtVentureX/sd-webui-agent-scheduler#109]
- Issue summary:
If there are pending tasks running, generation halts as soon as i switch to the Agent Scheduler tab. No choice at this point but to reboot A1111 (= Ctrl+C, then restart webui-user.bat), then queue restarts where it was. No preview show up though.
Most of the times it works, sometimes closing the CLI host window is necessary.
No error message, or anything. Feels like it's waiting for something that never comes.
In addition to that i do not have this issue on my other computer (see below for specs) with exact same configuration/extensions to the exception of what is listed below and startup options.

- Reproducibility:
Happens 100% of the times my side.
1. Prompt for anything, hit Generate. Set up a batch higher than 1 to give you some time. Generation starts.
2. Before it is finished, set up another prompt, hit Enqueue.
3. Switch to Agent Scheduler Tab
4. Progress bars stops after a few seconds in the CLI and GUI at any level it could have reached (e.g. 7/20 it). In the demo below it will stay at 14/20 forever.

I caught it on camera, this one time Ctrl+C in the CLI has no effect.
https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/35899920/8d6f0741-d81f-4166-95b8-ce6a50a4ca63

- Environment (real fresh, i just switched hardware):
Browser: Firefox
Agent Scheduler version: commit [e270493a](https://github.com/ArtVentureX/sd-webui-agent-scheduler/commit/e270493ab7c4b5cfb5eb39f474c34e51ebba8221)
Hardware (main): Gigabyte 4060 Ti OC 16GD, driver version 536.99 (latest as of time of writing)
Windows 11 22H2
Startup options: `--xformers --opt-split-attention --gradio-img2img-tool color-sketch --deepdanbooru --no-half-vae --update-check`

--------

Laptop (secondary pc) specs:
Browser: Firefox
Agent Scheduler version: commit bf3fc755 (i can try an update if needed)
Hardware: GTX 1660 Ti Mobile, driver 536.67 (here too but i don't know enough for to try a reinstall with a previous version)
Windows 11 22H2
Startup options: `--xformers --lowvram --deepdanbooru --no-half --no-half-vae --gradio-img2img-tool color-sketch --opt-split-attention --update-check`

This may be related to a recent extension commit, hardware/driver issue but at this point i'd better ask for directions first, i'm still a rookie with it.
Any help appreciated.

Thank you

---

Update: i might have narrowed it a bit: custom VAE + no use of `--no-half`/`--no-half-vae` seem to allow it to trigger.

**Comment by artventuredev** [comment]
That's odd, this issue shouldn't occur. I've been unable to replicate this on my Linux setup. It might be worthwhile trying again on a basic setup without any extensions.

**Comment by zethriller** [comment]
Well. That took me days to figure out this one.

As per https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9085#issuecomment-1575210881 it's more a "me" issue, and probably a combination of little too large batchs, live preview mode and live preview update frequency.

These work fine with any generation setting:
- Live preview rendering mode: **Full** --> **Approx NN** (seems it's the most important one)
- Batch size: **4** --> **2** also saves vram a blasted lot, increase batch count accordingly (smoothes out "transitions" a lot when ADetailer/Face Editor kick in)
- Live preview update steps every: **1 step** --> **2 steps**

Sorry about that. Nothing related with Agent Scheduler after all.

You can mark this one as closed :)

**Comment by artventuredev** [comment]
Great to hear you've solved it! I'll go ahead and close the issue. Keep up the good work! :)
