### ISSUE TITLE
Pinning tasks

### ISSUE THREAD

**Issue by Trevor-Z** [ArtVentureX/sd-webui-agent-scheduler#11]
This extension is very promising. A feature suggestion: It would be great to be able to pin the tasks to the queue, so they stay there after executing. Especially in addition to the ability to save/load and edit the tasks, as suggested in #9.

**Comment by vladmandic** [comment]
i'm guessing that's going to be part of what authors have on the roadmap - maintain history of jobs.

**Comment by Trevor-Z** [comment]
Sure, but it's a different workflow if you have to go to the logs and reload one or more tasks back to the queue every time, instead of having them pinned there.

**Comment by artventurdev** [comment]
Thanks for the suggestion, @Trevor-Z! We're already working on this feature and will release it in an upcoming update.
