### ISSUE TITLE
Runtime checkpoint

### ISSUE THREAD

**Issue by demoran23** [ArtVentureX/sd-webui-agent-scheduler#114]
Runtime checkpoint seems to just set the checkpoint to None.  

I was expecting it to look at the image metadata in img2img to determine the checkpoint the source image came from.

How does "Runtime Checkpoint" behave?

**Comment by tungnguyensipher** [comment]
It's the system selected checkpoint at the moment the task being executed.

**Comment by demoran23** [comment]
@tungnguyensipher Huh, I figured that was what "Current Checkpoint" meant.  

https://github.com/ArtVentureX/sd-webui-agent-scheduler/blob/86857553e715c8aa50f503dc2da320da8964e701/scripts/task_scheduler.py#L224 shows the conditions, but I guess I don't understand them.

What is the behavior of "Current Checkpoint"?

**Comment by tungnguyensipher** [comment]
Curent Checkpoint is the checkpoint that is currently selected in the top left checkpoint dropdown. When selected, the checkpoint name will be stored along with other params.

When select Runtime Checkpoint, checkpoint info is not stored, instead the extension will use what ever system checkpoint is at the execution moment. Normally you would want to use Current Checkpoint. For the behavior you're looking for, there's equivalent setting for that.
