### ISSUE TITLE
Iterate a list of prompts with a selection of models

### ISSUE THREAD

**Issue by Trevor-Z** [ArtVentureX/sd-webui-agent-scheduler#12]
As far as I know, there is no way to completely automate running the same set of prompts through a list of models, which is a way to test and compare checkpoints.

The X/Y/Z plot can loop one prompt through several models, and this extension can queue several prompts containing the X/Y/Z plot settings, but you have to add all prompts manually again for each run with a batch of new models.

So, I'd like to suggest this: a drop-down selector, like the one for Checkpoint name in the X/Y/Z plot, that allows us to select several models to sequentially run the queue through. Also, building on #11 , it would be even better if we could have a set of prompts pinned to the queue, and just select new models to run them on.

**Comment by AskTinNguyen** [comment]
Thanks for the suggestions!
Two options that currently address your use-case
1. This extension works with X/Y/Z plot
2. You can pick Model A, enqueue, pick Model B, enqueue...repeat until you have lined up all the tasks with models you need

<img width="1119" alt="Screenshot 2023-06-04 at 07 26 20" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/90659883/6d9ddcfe-d59f-490e-8d30-55eba3f15f1a">

**Comment by Trevor-Z** [comment]
Thanks. But that's the point, you'd have to start from zero every time you run the same set of prompts with a new batch of models.

Suppose you want to compare how a set of 30 prompts is rendered by 10 different checkpoints of a model that you are training or merging with different parameters. You'd have to manually configure and add 30 items to the queue in the first method, or 300 in the second. And you have to do it all again from scratch for more checkpoints later. And there is the possibility of error each time.

The idea here is, if we can pin a list of prompts to the queue, and then select a list of models to generate them in sequence, we only have to set things once. It's zero work after the initial set up.

Right now, it takes more time to set up all the prompts manually to test the results of model and lora merges than it takes to actually do the merges.

**Comment by AskTinNguyen** [comment]
You can try Dynamic Prompts (Wildcards) Extension to get the results you want.

Hope it helps!

**Comment by Trevor-Z** [comment]
Thanks. But like I said here, Dynamic Prompts doesn't offer the functionality needed for this use case: https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/2#issuecomment-1575462126

It doesn't work for prompts with different image sizes, different settings for steps and hires fix, different verbosity styles for prompts/negative prompts, etc.
