### ISSUE TITLE
Setting save error in Automatic WebUI 1.6 RC

### ISSUE THREAD

**Issue by aetherwu** [ArtVentureX/sd-webui-agent-scheduler#122]
AssertionError: Bad value for setting queue_history_retention_days: ['7 days', '7 days']; expecting str

**Comment by artventuredev** [comment]
Try edit the `config.json` file, remove the above config, save the file and try saving from the UI again.

**Comment by aetherwu** [comment]
> Try edit the `config.json` file, remove the above config, save the file and try saving from the UI again.

Cool. I will test it on RC for a while.
