### ISSUE TITLE
Hi-res ignored

### ISSUE THREAD

**Issue by MarkWar88** [ArtVentureX/sd-webui-agent-scheduler#129]
in 1.6.0 sd a1111 ui The hi-res settigs are ignored and image generate without it

**Comment by artventuredev** [comment]
Hi @MarkWar88, please make sure that the `Hires. fix` settings are expanded when you queue the tasks, otherwise they will be ignored.

<img width="740" alt="image" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/acaf2fb4-b23e-437a-ad03-8f0091b599fd">
