### ISSUE TITLE
Add ability to opt to auto-save a task-generated image

### ISSUE THREAD

**Issue by CptGabok** [ArtVentureX/sd-webui-agent-scheduler#13]
If I'm working without saving all generated images, then when running tasks, those images seem to just disappear. Being able to set all tasks to save their output would be great.

For example, the workflow I imagine is:

1. Generate many low-res images
2. Look through and mark the one(s) I want to do a highres fix pass on
3. Send those to the agent scheduler while I continue to generate low-res images

**Comment by AskTinNguyen** [comment]
Thanks for the suggestion!

Can you give me details what you, as a User would do in between Steps 1 to 3?

**Comment by CptGabok** [comment]
For sure!

For my specific use case, what I'd want is an option in the settings to "Always Save Queued Images" along with a path to save to.

I usually am trying out a prompt and generating a bunch of images to see which ones I'd like to do a higher res version on. So at the beginning of the session, I'd make sure "Always Save Queued Images" is enabled.

- I enter my prompt and I hit generate like normal.
- I get back a batch of ~8 images. I cycle through these generated images until I see one I like.
- I click "Hires. Fix" and adjust my settings.
- I specific the reuse seed (♻) of this particular image
- I click Enqueue to send this seed to the queue so it can be hires-i-fied.
- I disable Hires. Fix", set my seed to random (🎲), and generate a new batch of images.

Essentially, I am constantly looking through a batch of images for gems, and want a quick, easy way to flag "oh that's one I want to save and upres" without having to stop generated more batches. So maybe I generate 100, 5 are good, and those 5--one way or another--have been selected and queued to be upres'd.

**Comment by artventurdev** [comment]
Got your idea @CptGabok. I'll add this to the backlog.

**Comment by tungnguyensipher** [comment]
@vladmandic I planed to override the shares.opts.samples_save during generation, as it's doesn't make sense to queue a task without saving the images.

**Comment by vladmandic** [comment]
@tungnguyensipher i'm ok with that.

**Comment by artventurdev** [comment]
@CptGabok This feature is implemented on the latest commit, you can update the extension and give it a try.

**Comment by CptGabok** [comment]
Thank you!
