### ISSUE TITLE
Parallel tasks via API

### ISSUE THREAD

**Issue by harrywang** [ArtVentureX/sd-webui-agent-scheduler#132]
Thanks a lot for the great extension - I am wondering whether   parallel tasks can be processed at the same time - such as sending 5 tasks from different users to GPU to process at the same Time to better utilize the GPU and once the 5 tasks are done,send another 5.

Thanks!

**Comment by artventuredev** [comment]
This should be supported by the webui itself not the extension. And I believe it's not possible unless you have more than 1 GPU.

**Comment by harrywang** [comment]
> This should be supported by the webui itself not the extension. And I believe it's not possible unless you have more than 1 GPU.

Thanks for your reply！
