### ISSUE TITLE
can't callback https url

### ISSUE THREAD

**Issue by azoth07** [ArtVentureX/sd-webui-agent-scheduler#134]
ERROR:sd:{"status":2,"msg":"Unable to make protected java.lang.ClassLoader() accessible: module java.base does not \"opens java.lang\" to unnamed module @27abe2cd"}

**Comment by artventuredev** [comment]
Hi, is this error message from your backend? Can you confirm that the callback url is working properly?

**Comment by azoth07** [comment]
yeah, when I use the http url,  this error message is gone

**Comment by artventuredev** [comment]
I tested with HTTP and HTTPs and both are working properly. Can you queue (and run) 2 tasks with this data:

```json
{
  "prompt": "1girl",
  "negative_prompt": "text, watermark",
  "sampler_name": "DPM++ 2M Karras",
  "steps": 20,
  "cfg_scale": 7,
  "width": 512,
  "height": 512,
  "callback_url": "http://webhook.site/ae1d83c0-6758-4e4a-ae87-1b67ba17d778"
}
```

```json
{
  "prompt": "1girl",
  "negative_prompt": "text, watermark",
  "sampler_name": "DPM++ 2M Karras",
  "steps": 20,
  "cfg_scale": 7,
  "width": 512,
  "height": 512,
  "callback_url": "https://webhook.site/ae1d83c0-6758-4e4a-ae87-1b67ba17d778"
}
```

https://webhook.site is a utility website that provides webhook testing. You can also replace my URLs with your to test.
