### ISSUE TITLE
Controlnet is not working with API

### ISSUE THREAD

**Issue by Rakna123** [ArtVentureX/sd-webui-agent-scheduler#135]
I am using control net. I passed the data in JSON but it is getting discarded. In Output, control net is not included.
I am facing problem only in API and in WebUI it works.

This is my input
{
	"prompt": "Fire",
	"steps": 20,
	"sampler_name": "Euler a",
	"controlnet_units": [{
		"input_image": "image data",
                 "module": "canny",
		"model": "control_v11p_sd15_canny [d14c016b]",
		"weight": 1,
		"resize_mode": "Crop and Resize",
		"lowvram": false,
		"processor_res": 512,
		"threshold_a": 64,
		"threshold_b": 64,
		"guidance": 1,
		"guidance_start": 0,
		"guidance_end": 1,
		"guessmode": true
	}]
}

**Comment by artventuredev** [comment]
To use ControlNet, you can follow this example: https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/102#issuecomment-1707889940

```json
{
  "prompt": "1girl",
  "negative_prompt": "EasyNegative",
  "alwayson_scripts": {
    "controlnet": {
      "args": [
        {
          "enabled": true,
          "image": {
            "image": "https://d2lae7oxvyyfdd.cloudfront.net/poses/5609.jpeg" // or can be base64
          },
          "model": "control_v11p_sd15_openpose [cab727d4]"
        }
      ]
    }
  }
}
```
