### ISSUE TITLE
Where does Agent Scheduler keep its history?

### ISSUE THREAD

**Issue by trebory6** [ArtVentureX/sd-webui-agent-scheduler#136]
Hey guys, I'm trying to find the directory where Agent Scheduler keeps its history. 

This project doesn't have a discussions page so I had to ask here. 

I have a unique setup where I need to make symbolic links to sync up history with another instance I run,

Also is there a way to manually change how soon to delete history? Seems silly that the shortest option's a week and there's no option to delete history upon closing. 

Thanks!

**Comment by artventuredev** [comment]
It's the `agent_scheduler.sqlite3` in the extension folder. If you want to clear the history on every boot, just add a simple command to delete the file on startup.
