### ISSUE TITLE
RuntimeError: CUDA error: misaligned address CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by orion2199** [ArtVentureX/sd-webui-agent-scheduler#137]

**Comment by artventuredev** [comment]
This shoud not related to `agent-scheduler` but rather an `xformers` compatibility issue with one of your extension. Are you queueing AnimateDiff tasks, I have seen this bug recently when running `AnimateDiff`.

You may want to disable `xformers` by:
- remove the `--xformers` flag (if it's set)
- use other cross-attention optimization method be going to Settings -> Optimizations -> Cross attention optmization
<img width="446" alt="image" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/11b3f6e7-b604-4834-a701-5ba79c771a82">

**Comment by artventuredev** [comment]
If you're still experiencing this issue, this comment may help: https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/126#issuecomment-1743991142

**Comment by orion2199** [comment]
I tried this method.
The result is that I have not had any problems for 3 days.
Thank you.

2023年10月4日(水) 22:45 ArtVenture ***@***.***>:

**Comment by artventuredev** [comment]
Nice, I'll close the issue then.
