### ISSUE TITLE
Proposal for multi-selected checkpoints.

### ISSUE THREAD

**Issue by aetherwu** [ArtVentureX/sd-webui-agent-scheduler#139]
I notice that Automatic1111 provides support for a sub dictionary for checkpoints.
Is it possible to also support multiple checkpoints in specific subfolders?
For example, I could place all the checkpoints I want to test in a subfolder and then run them by right-clicking.
This solution does not require additional configuration or take up extra attention from new users.
It functions similarly to 'run for all checkpoints', but only within a subset defined manually by the user.

**Comment by artventuredev** [comment]
Thanks for the suggestion, that shouldn't be hard to implement. I'll take sometime implement this.

**Comment by artventuredev** [comment]
You can try this feature now with the latest update: https://github.com/ArtVentureX/sd-webui-agent-scheduler#queue-with-a-subset-of-checkpoints

**Comment by aetherwu** [comment]
It works like magic 💯 
Many many thanks 👯‍♀️
