### ISSUE TITLE
[Enhancement] - Task History "Save" button

### ISSUE THREAD

**Issue by Mistborn-First-Era** [ArtVentureX/sd-webui-agent-scheduler#141]
I would like to recommend a way to move to favorites or save a picture form the task history tab. When browsing my generations sometimes I find one that I would like to save. Currently I have to either regenerate it or navigate to it within the file explorer.

**Comment by artventuredev** [comment]
Could you provide more details about the Save action? Are you looking to locate the image on your disk, or is there another outcome you're seeking?

**Comment by Mistborn-First-Era** [comment]
The save action would either copy or move the file from the location where it is created into the folder called "favorites". The folder is set in the web ui 'settings' tab.

To test the currently built in 'save' setting there should be a button below the preview image. Here is a picture for reference. I would select one of the pictures I produce that I like and then select save to move it into my favorites folder. 

![2023-10-04 00_07_55-Stable Diffusion](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/100924753/47309099-3bfd-4a15-ae72-6131820e43f5)

![2023-10-04 00_10_11-S__Users](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/100924753/3eb03905-f6fb-490f-847c-4c0582f4dc61)

**Comment by artventuredev** [comment]
Got your idea. I'll add this feature to the backlog. Hopefully I can implement it this weekend.

**Comment by Mistborn-First-Era** [comment]
Thank you for your time, effort, and consideration!
