### ISSUE TITLE
Enque with all checkpoints failing at start

### ISSUE THREAD

**Issue by PaulBrousseau** [ArtVentureX/sd-webui-agent-scheduler#142]
When I choose enque with all checkpoint iconsole returns 

        File "F:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 213, in f
          task_name=task_name,
      UnboundLocalError: local variable 'task_name' referenced before assignment

a1111 = version: [v1.6.0]  •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [848144fa96]

queueing in general is working great and after enabling the checkpoint list i can queue them all up manually sop still a huge savings over no queueing option.  Just wante dto point out the bug and work around.

**Comment by artventuredev** [comment]
Gotcha, I'll put a fix for this soon.

**Comment by artventuredev** [comment]
I just deploy a fix, the issue should be resolved in the latest commit.

**Comment by PaulBrousseau** [comment]
Working great!  Makes SD so much easier for me to use,
