### ISSUE TITLE
[Bug] Checkpoint list does not appear

### ISSUE THREAD

**Issue by JingJang** [ArtVentureX/sd-webui-agent-scheduler#143]
When I try to edit the checkpoint, it only shows system in the listing. Not sure if this is a bug or not as I am new to this addon. 

If it is working as intended can you allow us to select a different checkpoint model. 

![Snap1](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/13469628/5d754888-a6ec-41b6-b344-1a4c750a982f)

SD Version Auto1111 1.6.0

**Comment by MMP0** [comment]
This extension uses APIs for listing checkpoints and sampling methods, so you should add `--api` to the command line arguments.

**Comment by JingJang** [comment]
Thank you
