### ISSUE TITLE
doesn't save the vae info

### ISSUE THREAD

**Issue by eli103** [ArtVentureX/sd-webui-agent-scheduler#148]
I scheduled for both SD1.5 and SDXL modules, and loaded Vae,  when it ran to SDXL module, I saw generated error pictures as it load the 1.5 version Vae.

**Comment by artventuredev** [comment]
I've just pushed a fix for this issue. Could you please try the latest commit and let me know if it resolves the problem?

**Comment by eli103** [comment]
Hi, thank you. It does fix the error pictures.  
and from the terminal, I can see it load the right vae when the agent ran.
