### ISSUE TITLE
--api-auth bug

### ISSUE THREAD

**Issue by joindn** [ArtVentureX/sd-webui-agent-scheduler#149]
When I add --api-auth admin:123456, the API can still be used without authentication. Is it possible to add authentication support?

**Comment by artventuredev** [comment]
I've added this feature in the latest commit. Please update and give it a test run.

**Comment by n0madic** [comment]
My Agent Scheduler tab does not work when `--api-auth` is enabled:
```
Request URL: https://sd.host/agent-scheduler/v1/queue?limit=1000
Request Method: GET
Status Code: 401 Unauthorized
```
```
Request URL: https://sd.host/agent-scheduler/agent-scheduler/v1/history?status=&limit=1000&offset=0
Request Method: GET
Status Code: 401 Unauthorized
```
In this case, the **Enqueue** button works without problems and tasks are added... If I disable authorization, they are visible.
