### ISSUE TITLE
/v1/task/id/results not have png metadata

### ISSUE THREAD

**Issue by faye1225** [ArtVentureX/sd-webui-agent-scheduler#150]
As shown in the title, I'm using the `/v1/task/id/results` interface to get task results, and the results are returned without the metadata.
```
{
  "success": true,
  "data": [
    {
      "image": "data:image/png;base64,iVBORw0KGgoAAAAN...",
      "infotext": "1girl\nNegative prompt: EasyNegative, badhandv4..."
    }
  ]
}
```
Since I'm working on node, I try to manually write the infotext to iTXt or tEXt.
But encountered some problems, Chinese, Russian, etc. can't be written well, or you guys can add this info when the interface returns? Or tell me what to do?

**Comment by artventuredev** [comment]
> the results are returned without the metadata.

Could you provide more details? Are you suggesting that the `infotext` is not being returned, that it's empty, or that there's no metadata embedded in the base64 encoded image?"

**Comment by artventuredev** [comment]
I believe I understand your issue now. There are no parameters embedded in the returned image. I've just added this feature in the latest commit. You can test it out.

**Comment by faye1225** [comment]
> I believe I understand your issue now. There are no parameters embedded in the returned image. I've just added this feature in the latest commit. You can test it out.

Sorry, I didn't respond to your question in time. But you are right, what I wanted to express is that the image returned by the interface in base64 does not have embedded metadata. Thank you very much for your reply, I will test it as soon as possible!
