### ISSUE TITLE
bug? restart queue processing - lost ability to start stop

### ISSUE THREAD

**Issue by terryrankine** [ArtVentureX/sd-webui-agent-scheduler#155]
Hi

If I terminate the app - then restart it - the queue starts processing again. which is great.
However
I seem to have no start and stop control over the queue.
I cant then stop the jobs - no matter what i try and do.
I can delete them - but cant pause/play the job or the queue initally.

after it has processed an entire line of the queue screen - i seem to be able to start interacting with the queue again.

I popped up debugger and the API call to /pause and /resume work - but the queue just keeps doing what it feels like.... until the first item (like a batch of 50) is done.

**Comment by tungnguyensipher** [comment]
If you want to pause the queue initially on startup (or after restart), head to Settings -> Agent Scheduler -> Tick the `Disable queue auto processing on startup`. The start/stop function doesn't cancel the already running task, you can only delete (terminate it).

**Comment by terryrankine** [comment]
No, I like that it restarted.

Once it starts, I can't pause it though. I can only pause after it's
processed the first item.

Pause resume doesn't do anything to the running job after it initially
restarts.

Pause resume works after it's finished it's first task though.

Or am I misunderstanding it?

Does pause resume do the queue level or the task level.

Queue:
Job 1: batch 20: fish
Job 2: batch 20: horse

Does pause resume work inside the batch? Does it pause at 12/20 fish? Or
does it only pause from starting the next job of horse?

**Comment by tungnguyensipher** [comment]
> Pause resume works after it's finished it's first task though. Or am I misunderstanding it?

The pause function applies only at the queue level, and individual tasks cannot be paused. Therefore, it might appear as though the pause function isn't working because the current task continues to run.

**Comment by terryrankine** [comment]
Thankyou for the explanation.

Pause resume is at queue level, not inside individual jobs.


Please close.
