### ISSUE TITLE
Feature Request: Re-add all failed jobs from history back into running queue

### ISSUE THREAD

**Issue by LankyPoet** [ArtVentureX/sd-webui-agent-scheduler#158]
Title says it all. I would like an easy way to re-add every failed job back into the queue to be processed.

Last night I received a CUDA out of memory error, and 100+ jobs "ran" but they errored out with the same error until I was able to shut down SD.NEXT. When I restarted, I was able to manually re-add the jobs from the task history, but a one-click solution would be great for this situation.

**Comment by artventuredev** [comment]
@LankyPoet, you now have the ability to re-queue all failed jobs using the `Requeue Failed` button located in the history tab.

Additionally, there's an option on the settings page that allows tasks to be automatically re-queued upon failure. However, please use this feature with caution as it may result in a task being queued repeatedly.

**Comment by LankyPoet** [comment]
Great! Thank you again!
