### ISSUE TITLE
When a job getting CUDA out of memory, it kills the whole queue

### ISSUE THREAD

**Issue by artventurdev** [ArtVentureX/sd-webui-agent-scheduler#16]
When one job CUDA OOM's out, it kills the whole queue. Would be great if it could auto-pause. Instead it errors out the whole queue CUDA'ing out because the memory isn't released.

_Originally posted by @zaileron in https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/2#issuecomment-1575922292_

**Comment by vladmandic** [comment]
if extension wants to check if oom occured in the backend, this is the new code:
```python
if getattr(shared.state, 'oom', False):
    print("OOM detected, exiting")
```

**Comment by artventurdev** [comment]
Queue now will pause if an OOM occur.
