### ISSUE TITLE
compatibility issue with 'dynamic prompt' regarding using a template (wildcard)

### ISSUE THREAD

**Issue by blueball81** [ArtVentureX/sd-webui-agent-scheduler#167]
Hi,

I used to use wildcard function using the dynamic prompt extension. 
When I turn on the "Save template to metadata: Write prompt template into the PNG metadata" option in the settings, the image file include the template of the prompt. However, when the image is created with this option, the task cannot be loaded in the task list as seen in the following capture.

<img width="966" alt="image" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/1153785/c0c696f3-7001-41d5-b682-a8b874693806">

**Comment by artventuredev** [comment]
I just added a fix for this, please update to the latest commit.

**Comment by blueball81** [comment]
It works now. Great!
