### ISSUE TITLE
can not use

### ISSUE THREAD

**Issue by LEONLAURA** [ArtVentureX/sd-webui-agent-scheduler#174]
TypeError: ControlNetUnit.__init__() got an unexpected keyword argument 'is_cnet'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
ERROR:sd:[AgentScheduler] Task task(hywlxa681mgaelt) failed:

**Comment by artventuredev** [comment]
The issue with ControlNet should be fixed with the latest commit.

**Comment by QuietNoise** [comment]
Had the same issue. The last commit fixed it. Thank you.
