### ISSUE TITLE
extension causing multiple unnecessary DOM updates during initial load

### ISSUE THREAD

**Issue by vladmandic** [ArtVentureX/sd-webui-agent-scheduler#18]
right now agent-scheduler in `ui/src/extension/index.ts` creates a callback for `onUiLoaded` which is ok in principle,
but note that callback is fired a LOT so there is a lot of JS code that executes over and over causing slower page load.

suggestion is to trigger initialization only once, for example:

```js
let agentSchedulerInitialized = false;

onUiLoaded(async () => {
  if (!document.getElementById('tab_agent_scheduler')) return; // simple check if components are created so init is not too early
  if (agentSchedulerInitialized) return; // already initialized
  initTabChangeHandler();
  initPendingTab();
  initHistoryTab();
  agentSchedulerInitialized = true;
});
```

note that this is a prototype code so you may need to tweak it further

**Comment by artventurdev** [comment]
Updated in #20.
