### ISSUE TITLE
incorrect extension folder structure causing scripts to be loaded multiple times

### ISSUE THREAD

**Issue by vladmandic** [ArtVentureX/sd-webui-agent-scheduler#19]
note that anything in `scripts` folder is automatically loaded by parent app - that is considered the entry point to extension.  

right now agent-scheduler has all its files there which is not how extensions should be structured.
and its causing slower than expected server startup as all those individual files are executed during startup sequence.

suggestion is to leave only `task_scheduler.py` in `scripts` and move all other files into extension root.
followed by change of import paths, so for example:

```diff
- from scripts.task_runner import TaskRunner, get_instance, task_history_retenion_map
- from scripts.helpers import log, compare_components_with_ids, get_components_by_ids
- from scripts.db import init, task_manager, TaskStatus
+ from task_runner import TaskRunner, get_instance, task_history_retenion_map
+ from helpers import log, compare_components_with_ids, get_components_by_ids
+ from db import init, task_manager, TaskStatus
```

(same change of import statements should be applied to all files)

**Comment by vladmandic** [comment]
btw, tagging @Mikubill as control-net has the same problem. if you want, i can create a separate issue in your repo?

**Comment by artventurdev** [comment]
@vladmandic I understand that all the files in the `scripts` folder will be loaded, but after seeing that `ControlNet` and `ImageBrowser` were organized in the same way, I decided to follow the same structure. I just moved all unrelated files out of `scripts`. #20

**Comment by vladmandic** [comment]
i know, i just started reaching out to all such extensions, i just started with agent-scheduler not because its the worst offender, but because you're most reponsive right now - so i can use it to showcase to other extensions "it can be done" ;)
