### ISSUE TITLE
[Feature Request] Queue with all [SD *or* SDXL] checkpoints

### ISSUE THREAD

**Issue by raffetazarius** [ArtVentureX/sd-webui-agent-scheduler#211]
Would be great to have the ability to queue a job with all checkpoints for a **specific SD version**, since SD vs. SDXL require different image sizes by default (512x512 for SD 1.5 vs. 1024x1024for SDXL) so if I did "Queue with all checkpoints", I'd get errors with either SD or SDXL depending on my image size.

In my installation, I have my models in subfolders inside my A1111 models directory:
SD 1.5
SD Turbo
SDXL 1.0
SDXL Turbo

So one solution could be to have all "Queue with all checkpoints in a specific **models subfolder**" (if you didn't want Agent Scheduler to have to understand every model's SD version, which I understand might be complicated).

**Comment by rjunk1** [comment]
> So one solution could be to have all "Queue with all checkpoints in a specific models subfolder"
Doesn't it already do this? I have my models in a multi-level folder hierarchy and I can queue at any level in the hierarchy.

**Comment by raffetazarius** [comment]
Ah so it does - apologies I missed this before. Thanks for your input.
