### ISSUE TITLE
Use machine locale for datetime conversation

### ISSUE THREAD

**Issue by Chubbly** [ArtVentureX/sd-webui-agent-scheduler#22]
Currently the Date field in the Agent Scheduler tab uses UTC(?) datetime to indicate when a Task was added. Would it be possible to use the locale of the machine instead?

And while I have you, would it be possible to show a start and end time for a task in the task history?

Thank you for the great extension!

**Comment by artventuredev** [comment]
@Chubbly This feature is implemented on the latest update.
