### ISSUE TITLE
[Feature] Setting to show image preview in relevant tabs

### ISSUE THREAD

**Issue by rushtothesun** [ArtVentureX/sd-webui-agent-scheduler#24]
Hello could you consider a setting to have image previews show in the relevant tabs rather than only in the Agent Scheduler tab?

**Comment by artventuredev** [comment]
@rushtothesun This feature is implemented on the latest update.

**Comment by rushtothesun** [comment]
> @rushtothesun This feature is implemented on the latest update.

Hello!

On the txt2img tab for example, I see that the image preview does work, however the image disappears from the preview box as soon as it is done generating as shown below. Would it be possible to have enqueue mimic the behavior of generate where the image stays in the box until the next image starts generating?

![1](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/20650932/63ac2e14-d102-44ab-bb17-69e42c0e3b0c)
![2](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/20650932/395b34b6-2324-43d4-b46c-a1f965f674ab)

**Comment by artventuredev** [comment]
@rushtothesun, while implementing the functionality you've suggested is not impossible, it is still a complex task. However, I have added a new setting that places the extension UI below the main UI. This allows you to quickly view the results without leaving the main tabs, hopefully providing a solution that meets your needs.

![Screenshot 2023-06-21 at 14 40 08](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/8c28eda0-3e17-4b23-a05d-b3f9c9a44ea3)


![Screenshot 2023-06-21 at 14 39 39](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/d412a203-164d-4982-b098-ea174f8fcd88)

**Comment by rushtothesun** [comment]
@artventuredev 

I tried that option however the generated image also disappears from the extension UI regardless of being in a tab or appended. This was mainly a small qol kind of request so don't sweat it if it's going to be a pain to implement.
