### ISSUE TITLE
[Feature] Callback for API mode

### ISSUE THREAD

**Issue by aetherwu** [ArtVentureX/sd-webui-agent-scheduler#25]
Appreciate your fantastic input and APIs.

As rendering one image takes an indefinite amount of time, could we please explore calling an external controller?

As an example, it can signal the external controller to retrieve the most recent outcomes of specific completed tasks:

CALLBACK POST to 'http://controllner_server/on_job_finished', 
POST parameters:
{
JobID: 1342,
URL: "/output/dir/00001_31234.png",
Parameters: "",
}

Accept result:
{
JobID: 1342,
}

Then controlle can do whatever it should do(requeue/clear single log/clear result/etc...)

**Comment by artventuredev** [comment]
@aetherwu Thank you for the suggestion. Added this to the backlog.

**Comment by artventuredev** [comment]
Unfortunately I haven't have time to work this feature yet. Hopefully I can get back to it in the next 1-2 weeks.

**Comment by artventuredev** [comment]
This feature is added in the latest commit: https://github.com/ArtVentureX/sd-webui-agent-scheduler#api-callback

**Comment by aetherwu** [comment]
Fantastic! Truly appreciate all the hard work you put into our community. Thank you so much!
