### ISSUE TITLE
AttributeError: module 'modules.script_callbacks' has no attribute 'on_before_reload'

### ISSUE THREAD

**Issue by meinbeitrag** [ArtVentureX/sd-webui-agent-scheduler#26]
In the CMD console I get the following error when starting the webui-user.bat:

Error executing callback app_started_callback for C:\Users\myname\stable-diffusion-webui\extensions\agent-scheduler\scripts\task_scheduler.py
Traceback (most recent call last):
  File "C:\Users\myname\stable-diffusion-webui\modules\script_callbacks.py", line 101, in app_started_callback
    c.callback(demo, app)
  File "C:\Users\myname\stable-diffusion-webui\extensions\agent-scheduler\scripts\task_scheduler.py", line 416, in on_app_started
    task_runner = get_instance(block)
  File "C:\Users\myname\stable-diffusion-webui\extensions\agent-scheduler\agent_scheduler\task_runner.py", line 491, in get_instance
    script_callbacks.on_before_reload(on_before_reload)
AttributeError: module 'modules.script_callbacks' has no attribute 'on_before_reload'

My webui-user.bat looks like this:
@echo off
set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--no-half
set REQS_FILE=.\extensions\sd_dreambooth_extension\requirements.txt
call git pull
call webui.bat

Could someone help me please? The "Enqueue" button appears and there is the "Agent Scheduler" tab in the UI but when I click it (the Enqueue button) nothing happens and there are not entries in the Agent Scheduler tab. :)

Have a great day,
Matthias

**Comment by artventuredev** [comment]
Hi @meinbeitrag, I believe that your SD webui version is a bit old and is lacking some of the needed functions. You can try to upgrade the SD webui (a simple git pull will do) and try again.

**Comment by meinbeitrag** [comment]
Hey @artventuredev, thank you for your fast answer. I was not able to update via git pull (from my understanding the "call git pull" also should have done this in my webui-user.bat). I got some error regarding to the launch.py. So I installed the complete Automatic1111 stable-diffusion-webui new and now your fantastic agent scheduler works! Thank you for your great work! All best, Matthias
