### ISSUE TITLE
Getting these weird messages on my terminal since I installed this extension

### ISSUE THREAD

**Issue by andupotorac** [ArtVentureX/sd-webui-agent-scheduler#34]
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"

And it happens as I don't interact with the enqueue button at all.
<img width="1716" alt="Screenshot 2023-06-21 at 22 16 50" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/3269738/873ba3af-73bb-48ae-a987-27dd0da5fba9">

I'm on a Mac.

**Comment by andupotorac** [comment]
Might be related to this oddly enough. IDK why it triggered now tho:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7984

**Comment by artventuredev** [comment]
I saw those messages but I am not sure where they came from. I'll investigate it.

**Comment by artventuredev** [comment]
@andupotorac I found it, should be fixed in the last commit.

**Comment by andupotorac** [comment]
> @andupotorac I found it, should be fixed in the last commit.

Thanks!
