### ISSUE TITLE
Keyboard hotkeys are not very functional

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [ArtVentureX/sd-webui-agent-scheduler#36]
I appreciate the intent with the keyboard hotkeys to Enqueue, but they don't work well.

Example of issues:
Letter = If you put just a letter as the input, you can't type that letter in the prompt window.
SHIFT + letter = If you do this, you can't type capital letters in the prompt window.
ENTER = Doesn't work.
SHIFT + ENTER = Doesn't work and triggers a normal render. Same for other combinations with enter.

**Comment by artventuredev** [comment]
@MNeMoNiCuZ 

This is how shortcut works. For single letter or Shift+letter, pick a letter you rarely use in the prompt, like ` or a number.
Enter alone is tricky because you need it for new lines. Avoid using it.
Shift+Enter is for generate action. I did some trick to override and it worked on my end - not sure why it doesn't work on yours.

**Comment by MNeMoNiCuZ** [comment]
Hmm, yeah, it just feels weird to be able to have a single letter as a hotkey, when you use letters to type prompts.
I found no comfortable hotkey, and there's no way to disable the hotkey. I guess this was my issue combined with the limitation of picking only the characters in the drop-down instead of any keyboard key (I understand why that limitation is there though, a lot of work to code nice key mapping solutions).

What hotkeys are you using on your end?

**Comment by MNeMoNiCuZ** [comment]
Considering CTRL + ENTER is the global GENERATE hotkey, I wanted to do it with some kind of ENTER combination. But I couldn't get them to work at all.
CTRL + ALT + ENTER would be my go-to, but not if it also starts a normal GENERATE, as it does now for me when I try the combination.

I think an option for no hotkey does make sense though and is probably a good feature to add.

**Comment by artventuredev** [comment]
Actually any combination with Enter can trigger the generate action, not just Ctrl + Enter.
The Shift+Enter and Ctrl+Shift+Enter are working fine on my end (I'm using a mac). I'll try it on a Windows machine to see if I can make it work.

Btw I added the setting to disable the feature on the latest commit, you can give it a try.

**Comment by brknsoul** [comment]
The default hotkey should not be Shift+<any printable>. Perhaps change the default to Ctrl+E.

**Comment by artventuredev** [comment]
Right, I updated the default to Ctrl+E.

**Comment by artventuredev** [comment]
Close as completed.
