### ISSUE TITLE
Notification: I added this extension to the webui extension index

### ISSUE THREAD

**Issue by w-e-w** [ArtVentureX/sd-webui-agent-scheduler#37]
I took the liberty in adding your extension to the webui extension index
if you wish I wish to make any changes to the description / tag or remove it from index please make pull request
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/commit/a2ac265ee8a62fb553379970804ff5398c1a30db

**Comment by artventuredev** [comment]
Awesome, loved to hear that! The description and tag look good to me.
