### ISSUE TITLE
Can't click the button

### ISSUE THREAD

**Issue by Tobe2d** [ArtVentureX/sd-webui-agent-scheduler#4]
Thank you so much for making this extention.

I have installed it and it show the new button "Enqueue" however I cant click the button ;-(
I went to settings and removed Hide the checkpoint dropdown and still the same.
Tested "Between Prompt and Generate button" and still I can't click the button "Enqueue"

When I click it literally nothing happens.

In the log it does not show any error.

What it could be?

**Comment by artventurdev** [comment]
@Tobe2d The `Enqueue` should change the text to `Queued` in about 1 second when clicked then back to Enqueue again.

Can you open the browser developer console (F12 or right click some where on the UI and select `Inspect`), capture the `Console` tab to see if there are any error message there.

You can also try to upgrade the A1111 to the latest commit and try again.

**Comment by Tobe2d** [comment]
Thanks for the reply @artventurdev 

The output of theF12 Console:
```
error
VM352:3 Uncaught (in promise) ReferenceError: submit_enqueue is not defined
    at Object.eval [as frontend_fn] (eval at <anonymous> (Blocks.svelte:67:25), <anonymous>:3:14)
    at je (Blocks.svelte:277:6)
eval @ VM352:3
je @ Blocks.svelte:277
Promise.then (async)
je @ Blocks.svelte:282
await in je (async)
(anonymous) @ Blocks.svelte:373
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
f @ Button.svelte:12
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
v @ Button.svelte:11
Show 4 more frames
```
The above is when I click on "Enqueue"

In regards to the upgrade I am on the latest update:

version: v1.3.1  
python: 3.10.11
torch: 2.0.1+cu118
xformers: 0.0.17
gradio: 3.31.0

**Comment by Ezekiel-Rage** [comment]
I'm having the same problem. The error I'm getting is identical to the one above though there is an earlier error that is generated when the page loads that read:
`[[Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.](extension.mjs:1)](http://localhost:7880/file=extensions-builtin/sd-webui-agent-scheduler/javascript/extension.mjs?1685812961.9794707)`

Running sd.next (vladmandic/automatic) 
Version: 549c02a8 Sat Jun 3 10:36:53 2023 -0400
Python 3.10.6 on Windows
Torch 2.0.1+cu118
Gradio 3.32.0

**Comment by artventurdev** [comment]
@Ezekiel-Rage Have you observed similar errors with any other JS scripts, or only with `sd-webui-agent-scheduler/javascript/extension.mjs?`

**Comment by Ezekiel-Rage** [comment]
I've had problems with other JS scripts in the past however those issues were the result of a gradio change. The change required certain configurations to explicitly grant permission for gradio to access paths outside its own working folder. The end result was several JS scripts being blocked as 403 forbidden. That issue have since been resolved. Unfortunately this one is entirely unique to sd-webui-agent-scheduler.

Here's a screenshot of the network > preview tab. I've also saved the information in the attached txt file if you need more info than the screenshot can provide.

![Network_2](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/37027067/5d522fe1-56cd-4505-81d4-99f949b3ae07)

[Agent_Scheduler_Network_Preview.txt](https://github.com/ArtVentureX/sd-webui-agent-scheduler/files/11644860/Agent_Scheduler_Network_Preview.txt)

**Comment by artventurdev** [comment]
The js content look correct. I'll take a deeper look on how how these js files are handled by gradio.

**Comment by Tobe2d** [comment]
@artventurdev 
In regards to your question I am not sure if I had errors with any other JS scripts.

 here is the screenshot:
![image](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/4099839/1ddb0004-1188-4230-957a-094e67bb2bbe)

And the preview tab:
[Preview.txt](https://github.com/ArtVentureX/sd-webui-agent-scheduler/files/11645920/Preview.txt)

**Comment by artventurdev** [comment]
@Tobe2d @Ezekiel-Rage, it seems that there may be an issue with Python returning the wrong mimetype for the `.mjs` file.

If possible, please add the following debugging code to `webui.py` so it runs using the same Python version:

```python
from mimetypes import guess_type

print("mjs mimetypes", guess_type('/extension.mjs', True))
```

Restart the webui and check the logs for the output, which should look like this:

```
mjs mimetypes ('application/javascript', None)
```

If instead the output is `text/plain`, you can try the following steps:
- Reinstall Python
- Remove the venv folder and let the webui reinitialize.

**Comment by Ezekiel-Rage** [comment]
The output was: 
`mjs mimetypes ('text/plain', None)`

I'll try your suggestions later tonight when I have some free time.

**Comment by Ezekiel-Rage** [comment]
I tried removing the venv folder and letting it reinitialize but no luck. After some investigation I found the cause of my issue to be a registry error. `Computer\HKEY_CLASSES_ROOT\.mjs` had the `Content Type` set to `text/plain`. I reset it to `application/javascript` and rebooted and everything is working now.

**Comment by artventurdev** [comment]
Nice catch @Ezekiel-Rage.

@Tobe2d Can you try the above registry fix, it should also fix yours.

**Comment by Tobe2d** [comment]
Thanks @artventurdev editing the registry works for me ;-)

**Comment by shlomitgueta** [comment]
> 

@artventurdev  works for me too :)
