### ISSUE TITLE
stable-diffusion-webui-ux the queue button will not appear on the interface

### ISSUE THREAD

**Issue by evakenshin** [ArtVentureX/sd-webui-agent-scheduler#41]
"This plugin is not compatible with the installation on https://github.com/anapnoe/stable-diffusion-webui-ux, and the queue button will not appear on the interface. Can it be fixed?"

**Comment by evakenshin** [comment]
![744261d5ec9f435ab12aeec47b9a485](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/13158959/5b3f891e-4030-44a5-9f83-de5b48fadfa0)
"The page freezes on the initial load and requires a page refresh for the button to appear. After refreshing the page, the button appears, but the task list does not show up for both the historical and current queues upon clicking the queue interface."

**Comment by artventuredev** [comment]
Hi @evakenshin, I added some basic support for [stable-diffusion-webui-ux](https://github.com/anapnoe/stable-diffusion-webui-ux) on the last commit. You can give it a try.

**Comment by evakenshin** [comment]
nice thanks
