### ISSUE TITLE
NameError: name 'initialized' is not defined

### ISSUE THREAD

**Issue by DrJKL** [ArtVentureX/sd-webui-agent-scheduler#43]
Hey all,

Getting this error in the console. I'm not sure that it's doing what it's expected to.

https://github.com/search?q=repo%3AArtVentureX%2Fsd-webui-agent-scheduler%20initialized&type=code

https://www.askpython.com/python/examples/python-global-name-not-defined-error

**Comment by artventuredev** [comment]
Should be fixed in the last commit.
