### ISSUE TITLE
PNGINFO stops working.

### ISSUE THREAD

**Issue by watdomo** [ArtVentureX/sd-webui-agent-scheduler#44]
If you install and enable sd-webui-agent-scheduler, you will not be able to read the prompt embedded in the image even if you specify the image in PNG info. sd-webui-agent-scheduler can be disabled and you will be able to read it. sd-webui- agent-scheduler is affecting this.

**Comment by artventuredev** [comment]
I'm unable to reproduce this on my end. Please provide more information for debugging:

- What's your SD version, commit hash
- The SD console log: is there any error message
- The browser log: Open browser press F12, go to console tab, then refresh the page with F5, go to PNG info and check the console tab for any error message.

**Comment by artventuredev** [comment]
Close issue due to inactivity.
