### ISSUE TITLE
Use with scripts?

### ISSUE THREAD

**Issue by Vektor369** [ArtVentureX/sd-webui-agent-scheduler#45]
There's no way to use this with scripts like Ultimate SD Upscale though, right? It would be amazing if you could. I can't find a way to do it (outside of custom-creating a clunky macro.) Batch Count doesn't even seem to work with it.

**Comment by artventuredev** [comment]
Scripts should work normally. I haven't try the `Ultimate SD Upscale`, but builtin scripts like `XYZ Plot` are working just fine. 

<img width="836" alt="Screenshot 2023-06-26 at 02 50 14" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/dca58ee3-973c-4bf9-bce1-8b0ea90dba1f">

If some scripts are not working, please check the SD console and look for error messages if any.

**Comment by artventuredev** [comment]
Close issue due to inactivity.
