### ISSUE TITLE
Result loading time, ignoring parameters of X/Y/Z plot

### ISSUE THREAD

**Issue by freezerain** [ArtVentureX/sd-webui-agent-scheduler#46]
When generating X/Y/Z plot script you can see 2 checkmarks "Include sub images" and "include subgrids"
They responsable for showing in normal result window individual images or batches (2x2 matrix for batch of 4).
When both disabled only final plot matrix presented. However extension is loading everything which making some of my task results to load for more then 90 seconds and I got samsung 980 pro ssd
The extension should respect X/Y/Z plot settings or expose its own variables in setting tab.

I also noticed that images are loading from the c:/bullshit/temp folder and not from output/txt2imggrids folder, while in theory there are should be any difference in loading speed, it worth while to investigate as I noticed longer then usual loading of very heavy (50k*4k pixels) matrix. However this can come from the fact this image is not opened directly by me as usual but procesed through python envirenment.

thank you amazing extention (while im here history clean button will be cool to have)

**Comment by artventuredev** [comment]
> extension is loading everything

Although the `Include sub images` and `include subgrids` options are not checked, SD still persist all generated images to disk if you enable save images/grids in the settings. The extension collects all persisted images as results, thus also includes images that are not displayed in the result gallery.

> I also noticed that images are loading from the c:/bullshit/temp folder and not from output/txt2imggrids folder

This is the way gradio gallery (the image viewer component) handles image preview, it's not specific to the extension.

> history clean button will be cool to have

Clean history is a good feature to add, I'll put it to the backlog.

**Comment by artventuredev** [comment]
The file loading and displaying is handled by the browser when you drop the file directly to it. The current image viewing method of gradio might be too slow in some situations. This issue requires further debugging and optimization in gradio library.
