### ISSUE TITLE
Incorrect Enqueue button Placement Automatic1111

### ISSUE THREAD

**Issue by neilmahaseth** [ArtVentureX/sd-webui-agent-scheduler#48]
The Enqueue button is visible in the footer section in img2img when the location is set to the Under Generate button. Enqueue button is not visible if set to Between Prompt and Generate button. 

version: [v1.4.0-RC](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/3b11f17a374520e493e120e7f47443acd97393c8)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: [4199bcdd14](https://google.com/search?q=4199bcdd147e11328d5f3560301d5a7ab4ac7eeefbf49dc3eb663cb3e772b9ac)

![Incorrect Enqueue Button Location](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/7073681/cdf84145-c9f5-40be-b743-c591b9d9f6a7)

**Comment by artventuredev** [comment]
You can just wait a few seconds then reload and the button should be in the correct position.

**Comment by neilmahaseth** [comment]
No, It looks to be some bug. The same button is visible on the extras page also. #47

**Comment by artventuredev** [comment]
Hmm then there maybe some changes in the webui layout, let me see if I can reproduce this.

**Comment by artventuredev** [comment]
@neilmahaseth I'm not able to reproduce the issue on my end so I'm just guessing the cause. Please try the latest commit and check if the issue is fixed.

**Comment by neilmahaseth** [comment]
Thanks for looking into the issue. I have tried it out. The latest commit fixes the problem.
