### ISSUE TITLE
Enqueue button starts render immediately; Pause doesn't work

### ISSUE THREAD

**Issue by don1138** [ArtVentureX/sd-webui-agent-scheduler#5]
## App and OS versions

Apple M1 Max 32Gb
Ventura 13.4

python: 3.10.10
torch: 2.0.0
xformers: N/A
gradio: 3.16.2
commit: [4b159292](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4b1592926dd9863086480f9317d5c7fe88526e1a)

## Describe the bug

GREAT extension, but one bug on my system: when I hit the **Enqueue** button, the render starts immediately.

Each job I add using the **Enqueue** button renders perfectly fine, but:

- No items show up in the **Task Scheduler** tab
- The **Pause** button has no effect
- The **Refresh** button has no effect

I'm on a Macintosh, using the [brkirch custom build](https://github.com/brkirch/stable-diffusion-webui/releases/tag/20230330) released March 30.

## Error message
```
Error executing callback app_started_callback for /Users/user/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/api.py
Traceback (most recent call last):
  File "/Users/user/stable-diffusion-webui/modules/script_callbacks.py", line 107, in app_started_callback
    c.callback(demo, app)
  File "/Users/user/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/api.py", line 119, in on_app_started
    task_runner = get_instance(block)
  File "/Users/user/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/task_runner.py", line 431, in get_instance
    script_callbacks.on_before_reload(on_before_reload)
AttributeError: module 'modules.script_callbacks' has no attribute 'on_before_reload'
```

**Comment by artventurdev** [comment]
Hi @don1138, I suspect that your A1111 version is a bit old and is lacking some of the needed functions. You can try to upgrade the A1111 is self (a simple git pull will do) and try again. 

One more thing, if you want to always pause the queue at start up, you can check the `Disable queue auto processing` in the setting tab.

**Comment by don1138** [comment]
Ah, well -- since I'm running a old version of SDUI, I expected there wasn't anything to be done about it, but I thought I'd ask on the off chance that you'd have a quick, "change Line 375 from `.autorun()` to `.legacy_autorun()`" (or something like that) at hand that would get it up and running.

`Disable queue auto processing` pauses the cache, but as I mentioned, the **Agent Scheduler** is a dead window -- no buttons work, no jobs list appears -- so there's no way to get the queue running again.

The extension works perfectly in my install of the latest SDUI, so I can use it there, but unfortunately there are Mac incompatibilities in the current version, so the legacy install is where I do most of my work.

In any case, thanks for your response!

If there's nothing more to be done, then feel free to close this issue.
