### ISSUE TITLE
Latest fix seems to reverse the order of elements in SD.Next's UI

### ISSUE THREAD

**Issue by brknsoul** [ArtVentureX/sd-webui-agent-scheduler#50]
Using [SD.Next](https://github.com/vladmandic/automatic) the latest commit c305809 seems to reverse the order of UI elements;

![image](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/1969381/7ad27d4d-32a3-48b2-af22-dbe5b89da40b)

This fixes itself if the Queue button placement > Between Prompt and Generate button setting is used.
![image](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/1969381/fa333e1a-46f6-4416-93d9-2f60d3e99f11)

**Comment by andupotorac** [comment]
Same here, and it also at times just prevents generating new images in the main txt2img tab. I've disabled this extension and now it works again.
<img width="1249" alt="Screenshot 2023-06-26 at 21 06 05" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/3269738/fc53383c-378e-4a47-82c5-ed07f13f4773">

**Comment by tungnguyensipher** [comment]
@andupotorac Sorry for the inconvenient. What's your webui commit/version?

**Comment by artventuredev** [comment]
@brknsoul The issue should be fixed in the last commit. 

@andupotorac I don't know your exact webui commit, but I suggest you do an update for both webui and extension then try again.

**Comment by brknsoul** [comment]
> The issue should be fixed in the last commit

Thank you. All fixed!
I love this extenstion.. so handy!

**Comment by andupotorac** [comment]
> 

version: [v1.4.0-5-gef9ffa1b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ef9ffa1ba48ff3e3ccc962c238cecfead030ecc4)  •  python: 3.10.12  •  torch: 2.0.1  •  xformers: N/A  •  gradio: 3.32.0  •  checkpoint: [ef49fbb25f](https://google.com/search?q=ef49fbb25fa908bb54ded95abf81ef4b0e21fa0a8de56c40c3d62e768ef7e49a)

**Comment by andupotorac** [comment]
> @brknsoul The issue should be fixed in the last commit.
> 
> @andupotorac I don't know your exact webui commit, but I suggest you do an update for both webui and extension then try again.

I'm using the latest.

**Comment by artventuredev** [comment]
Have you try update the extension to the latest commit yet? If it's still not working, please post the list of installed extensions and there versions (a capture of the extension tab should do the job).

**Comment by andupotorac** [comment]
Will do, didn't try it yet. Need to schedule a few hundred prompt generations these next few days and will tell you how that works.

**Comment by andupotorac** [comment]
Alright, so I let it run overnight with 66 queued tasks, man what a lifesaver. Yes, it worked as expected now, the UI isn't broken anymore. Thanks!!
