### ISSUE TITLE
Pressing the Enqueue button doesn't do anything

### ISSUE THREAD

**Issue by boog2dan** [ArtVentureX/sd-webui-agent-scheduler#52]
Hi, 

the extension seems to be running:
[AgentScheduler] Task queue is empty
[AgentScheduler] Registering APIs

but pressing the Enqueue button doesn't do anything. I know from my home machine that it should change briefly to Enqued. 
No message comes up on the console either.

I got it to work at home machine, with the same extensions installed as work (where it doesn't work).

- Cozy-Nest
- OneButtonPrompt
- SDAtom-WebUi-us
- canvas-zoom
- sd-webui-agent-scheduler
- sd-webui-ar
- sd-webui-aspect-ratio-helper
- sd-webui-controlnet
- ultimate-upscale-for-automatic1111
- LDSR
- Lora
- canvas-zoom-and-pan
- extra-options-section

all up to date as of today. 
version: [v1.4.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/394ffa7b0a7fff3ec484bcd084e673a8b301ccc8)
 •  python: 3.10.6
 •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  
⠀•⠀Cozy Nest: [v2.3.3]

Thank you.

**Comment by artventuredev** [comment]
Please try this: https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/4#issuecomment-1575986274

**Comment by boog2dan** [comment]
thank you, that works. 

just one mention - after the web interface is loaded for the first time, it does not work. 
but after refreshing the browser one time it works perfectly.
