### ISSUE TITLE
Extension JS code may be blocked

### ISSUE THREAD

**Issue by vladmandic** [ArtVentureX/sd-webui-agent-scheduler#54]
Depending on OS/browser settings, loading of extension js file `extension.mjs` may be blocked 

```log
[[Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.](extension.mjs:1)](http://localhost:7880/file=extensions-builtin/sd-webui-agent-scheduler/javascript/extension.mjs?1685812961.9794707)
```

This is a known issue already discussed in #4 and https://github.com/vladmandic/automatic/issues/1506 and i feel this is going to happen more and more in the future. And while solution provided is fully viable and clean, its not reasonable to expect users to edit registry  for normal functionality.

Normally I'd say that ES is preferred format for JS, but the issue here is that all JS files are served by `gradio` using generic `/file=` functionality, there is no way to set proper MIME type handling (ok, doable via custom fastapi middleware, but that may be going too far).

Suggestion is to modify `vite.config.ts`
- change vite build target (`build.lib.formats`) from `es` to `iife`  
- change build destination file (`build.lib.fileName') from `extension` to `agent-scheduler`  
  (current name is misleading to start with)

**Comment by artventuredev** [comment]
Agreed, I already planed to do this since more and more people getting the issue. Btw I just update the format to `iife`, should be good now.

**Comment by vladmandic** [comment]
thanks!
