### ISSUE TITLE
AgentScheduler Extension Tab.

### ISSUE THREAD

**Issue by abragano** [ArtVentureX/sd-webui-agent-scheduler#60]
everything seems loaded, but i have no AgentScheduler Extension Tab.

**Comment by artventuredev** [comment]
I can't do much without any useful information. Please provide your:
- SD webui version/commit hash (It's in the webpage's footer)
- SD webui console log (Restart the webui and copy all the boot log)
- Browser console log (Open browser then press F12 -> console tab and grab any error message here)
