### ISSUE TITLE
Feature Request: Folder or Indicator Feature (similar to bookmark)

### ISSUE THREAD

**Issue by Tikishark777** [ArtVentureX/sd-webui-agent-scheduler#61]
I want the ability to sort previous jobs or the option to either place past jobs into folders or add a keyword or indicators.  For example, sorting old jobs into Top 10, Redo folders, etc.  Thank you for your time.  This extension has greatly improved my workflow.

**Comment by artventuredev** [comment]
I'm glad that the extension can help you. Currently, the extension has some features that may partially meet your needs:
- You can double click the task id and give it a name you like, then search for it again with the search box.
- You can click the bookmark icon at the start of each row to pin a task, then filter by status or click the column header to sort the pinned tasks to the top.

**Comment by Tikishark777** [comment]
Thank you, that was exactly what I was looking for.  I appreciate your help.
