### ISSUE TITLE
Lost the buttons column?

### ISSUE THREAD

**Issue by PaperOrb** [ArtVentureX/sd-webui-agent-scheduler#66]
Maybe I missed it, but I didn't see any issues on how to retrieve a column in the task queue if you accidentally drag it off to the right. I used the arrow keys to move to the far right column, but I still didn't see the play and delete buttons column.

**Comment by artventuredev** [comment]
You can try to clear the browser cache, it should be back.

**Comment by PaperOrb** [comment]
Thanks, I had to clear cookies as well to get it fixed.
