### ISSUE TITLE
Is there any update on callback of the api mode please?

### ISSUE THREAD

**Issue by Bruce337f** [ArtVentureX/sd-webui-agent-scheduler#70]
In addition, can **the priority** be changed through parameters? For example, if I want to limit the **running configuration** of a certain task, how should I do it?

It's good project!

**Comment by artventuredev** [comment]
It's now available in the latest commit. You can read the doc here for more detail: https://github.com/ArtVentureX/sd-webui-agent-scheduler#api-callback
