### ISSUE TITLE
post api /agent-scheduler/v1/queue/txt2img has been blocked by CORS policy

### ISSUE THREAD

**Issue by JonasTrinh** [ArtVentureX/sd-webui-agent-scheduler#74]
localhost develop:
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by JonasTrinh** [comment]
I already add arg 

> --cors-allow-origins=*

/sdapi/v1/txt2img works
but
/agent-scheduler/v1/queue/txt2img not work

**Comment by artventuredev** [comment]
That's strange! It's running perfectly fine on my end, and both APIs are served by the same FastAPI server, so there shouldn't be any issues. Have you checked the console log? Failed API calls can sometimes result in CORS errors as well.
