### ISSUE TITLE
installing breaks png info, image browser, and load last prompt/generation settings

### ISSUE THREAD

**Issue by ArchAngelAries** [ArtVentureX/sd-webui-agent-scheduler#75]
Really love this extension, but I've tried installing it a couple times now and every time I install it breaks functionality for PNG Info, Image Browser Extension, and the reload last prompt/generation prompt & settings button. Uninstalling fixes the issue. I hope a fix can be made soon.

**Comment by artventuredev** [comment]
Can you provide some information for debugging:
- Your SD webui version/commit hash
- List of installed extensions and their versions (You can capture the extension tab)
- SD startup log
- Browser console log (press F12 on browser, go to Console tab, refresh the page and copy error logs if any)

**Comment by ArchAngelAries** [comment]
Never mind, After updating the extension to latest commit everything works. Thanks for trying to assist :)
