### ISSUE TITLE
Dragging items in the list to change their order doesn't work.

### ISSUE THREAD

**Issue by andupotorac** [ArtVentureX/sd-webui-agent-scheduler#79]
It shows the item that is being dragged, but when released, nothing happens.

Chrome Version 114.0.5735.198 (Official Build) (arm64), on Mac OS.

**Comment by artventuredev** [comment]
I've addressed the problem and fix it in the latest commit. Please update the extension and give it a try. Just keep in mind that the fix may only apply to new tasks, while previously queued tasks might still be affected.

**Comment by andupotorac** [comment]
Thanks!
