### ISSUE TITLE
[Feature]Should support api query task status

### ISSUE THREAD

**Issue by zhzLuke96** [ArtVentureX/sd-webui-agent-scheduler#86]
When I want to use task_id to query the task status, I found that the current API cannot do this
Although, it is possible to pass `/agent-scheduler/v1/results/{id}`
This interface queries task result, but cannot get the status accurately

I think there is a great need for an interface to query the status of tasks. In addition to the status of `running/failed/...`, there is also a need to query of `task progress` and `eta`, just like `/sdapi/v1/progress`

maybe like:
```
GET /agent-scheduler/v1/task/{id}
```

What do you recommend? How to unify the task state inside agent-scheduler and the task state in webui?

**Comment by artventuredev** [comment]
> When I want to use task_id to query the task status, I found that the current API cannot do this

Nice catch, I'll add an API for this. 

> I think there is a great need for an interface to query the status of tasks. In addition to the status of `running/failed/...`, there is also a need to query of `task progress` and `eta`, just like `/sdapi/v1/progress`

You can just use the `/internal/progress` API, which accept `task_id` as input.

**Comment by artventuredev** [comment]
@zhzLuke96 I added a new API to get the task detail (status, params) by id on the latest commit. If the status is `running`, then you can get the execution progress via `/internal/progress` API.

**Comment by miaoihan** [comment]
When I call the '/agent-scheduler/v1/queue/txt2img' endpoint and then call '/task/:id' API, the returned status is correct. However, when I call '/agent-scheduler/v1/queue/txt2img', there is an issue with the status. It does not return the correct status as expected.

**Comment by tungnguyensipher** [comment]
The task created via `/sdapi/v1/txt2img` is not managed by this extension. So done use the `task_id` from SD's APIs to call extension APIs.

**Comment by artventuredev** [comment]
The task created via `/sdapi/v1/txt2img` is not managed by this extension. So done use the task_id from SD's APIs to call extension APIs.
