### ISSUE TITLE
Feature request: can I dispatch multiple checkpoint tasks in one submit?

### ISSUE THREAD

**Issue by aetherwu** [ArtVentureX/sd-webui-agent-scheduler#88]
One of my big pain in testing in webui is to go through different models. With AgentScheduler, it relieves this tension a lots and big thank you for all dev here!

One more thought is that: Can I quickly go through my 40-50 models, and check all models I'd like to test, and submit them in one time? I know it might bring more questions in detail - for instance, would it keep all checked options for next use? Should there be a simpler script to do it? 

Just jump in here and to share my ideas. 💯

**Comment by artventuredev** [comment]
@aetherwu  On the latest version you can right click on the `Enqueue` button and select `Queue with all checkpoints`. Right now there's no option to queue with a subset of the checkpoints, I'll improve this feature when I have time.

<img width="305" alt="Screenshot 2023-07-25 at 05 24 02" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/fbbed7a1-6a3f-4cab-8091-110455d3bd6e">

**Comment by aetherwu** [comment]
> @aetherwu On the latest version you can right click on the `Enqueue` button and select `Queue with all checkpoints`. Right now there's no option to queue with a subset of the checkpoints, I'll improve this feature when I have time.
> 
> <img alt="Screenshot 2023-07-25 at 05 24 02" width="305" src="https://user-images.githubusercontent.com/133728487/255736286-fbbed7a1-6a3f-4cab-8091-110455d3bd6e.png">

"You've discovered a hidden treasure box." 😆
