### ISSUE TITLE
How to effectively cancel or prohibit the automatic saving of pictures generated through the API?

### ISSUE THREAD

**Issue by Bruce337f** [ArtVentureX/sd-webui-agent-scheduler#89]
When I modify the program in the api, and comment out some codes that seem to need to be canceled, but through the api call, the picture will still be generated to the corresponding directory folder?

this is code block location:
[https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39/modules/api/api.py#L181-L186](url)
```
populate = txt2imgreq.copy(update={ # Override __init__ params
            "sampler_name": validate_sampler_name(txt2imgreq.sampler_name or txt2imgreq.sampler_index),
            "do_not_save_samples": False,	
            "do_not_save_grid": False,
            "outpath_samples":no opts.outdir_txt2img_samples,	#you can set another folder if you want, I didn't test it though 
            "outpath_grids": no opts.outdir_txt2img_grids,
            }
        )
```
I tried this code,but it's useless for me!

**Comment by artventuredev** [comment]
> When I modify the program in the api, and comment out some codes that seem to need to be canceled, but through the api call, the picture will still be generated to the corresponding directory folder?

Hmm, I'm not really get your idea. Are you mentioning the original SD APIs (`/sdapi/txt2img`) or the queue APIs from the extension (`/agent-scheduler/v1/queue/txt2img`)?


> I'm very sorry, I don't quite understand the function of the callback function, do I need to pass parameters to query the task status, why not directly return the progress or status of the image generation?

This is the example code you should implement on your end end handle callbacks from the extension. Explicitly, the body contains 3 fields:
- task_id: the id that are returned when you queue a task
- status: can be `done` or `failed`
- files: list of generated images

**Comment by artventuredev** [comment]
> It should be the api in the original sd,`/sdapi/txt2img` because I have modified your code, but it has no effect.

If you're calling the `/agent-scheduler/v1/queue/txt2img` API, then the generated images will always be saved.
If you're calling the `/sdapi/txt2img` API, you can pass the param `"save_images": false` to the request. Eg:

```
POST /sdapi/txt2img
{
  "prompt": "1girl",
  ...
  "save_images": false
}
```

> I don't quite understand why parameters are passed, especially status, shouldn't this be the result returned by the extension itself? If you still need to pass parameters, it will become a custom image state?

The code provided is an example for implementing the callback API handler on **YOUR SERVER**. If you're not using the callback feature, you can simply ignore it. The purpose of the callback API is to be called by the extension when the task is completed. The status parameter is included in the body to indicate whether the generation was successful or not. Please note that the handler should be mapped to an API endpoint and not called as a function directly.

**Comment by tungnguyensipher** [comment]
> Is there any update here please?

@Bruce337f This's mostly because your callback is not accessible from your SD node. What's your callback_url setting?

**Comment by artventuredev** [comment]
You should just ignore the `callback_url`, don't set it in your request body. The callback is to notify a remote server when a task is completed.
