### ISSUE TITLE
Enhancement: ability to save tasks

### ISSUE THREAD

**Issue by neuralweights** [ArtVentureX/sd-webui-agent-scheduler#9]
First of all thank you so much for this brilliant extension, I think I will use it a lot in the future. I know that there is a log for the tasks but it crossed my mind wouldnt it be great to be able to save tasks and categorize them, so that at a later point I can use the agent scheduler a bit like a library, select a task, send it to txt2img or img2img and edit it, and enqueue it again? Basically like the saved styles in the webui but it encompasses ALL the script settings etc.

**Comment by davedfx** [comment]
yes the save and load feature will be really useful! This was what I was looking for when I first tested this extension.

**Comment by artventurdev** [comment]
@neuralweights @davedfx We just rolled out the new version with some new features:
- History log
- Bookmark any tasks
- Rename a task
- Re-generate a task
- Show generated images
- Send params directly to txt2img, img2img

You can read more about the new functionality in the README.
