### ISSUE TITLE
Controlnet params won't be set when using Text2Img in Task History Tab。

### ISSUE THREAD

**Issue by gamert** [ArtVentureX/sd-webui-agent-scheduler#94]
This MVP extension is a great job！

**Comment by artventuredev** [comment]
Do you mean the ControlNet parameters are not set when you click `Send to txt2img`? I also want to have this feature but SD webui doesn't support it.

**Comment by gamert** [comment]
> Do you mean the ControlNet parameters are not set when you click `Send to txt2img`? I also want to have this feature but SD webui doesn't support it.

Yes。 But what a pitty~
