### ISSUE TITLE
In Task History Tab ，The Task Time Should use Local Time？

### ISSUE THREAD

**Issue by gamert** [ArtVentureX/sd-webui-agent-scheduler#95]
Is it a UTC time now ？

**Comment by artventuredev** [comment]
It's local time on the latest version. What's the commit you are using? You may want to update the extension and try again.

**Comment by gamert** [comment]
![1691133204993](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/6113801/b79a3c7f-ae0c-444d-9a48-ac1fc00b7742)
My Local  Time is 2023/8/4 15:15 In ShangHai, China. So I think something is still wrong.

**Comment by artventuredev** [comment]
@gamert  The issue should be fixed in the latest update, please give it a try.

**Comment by gamert** [comment]
> @gamert The issue should be fixed in the latest update, please give it a try.

yeal，Sure it.
