### ISSUE TITLE
Is it possible to generate the same percentage progress as sd please?

### ISSUE THREAD

**Issue by Bruce337f** [ArtVentureX/sd-webui-agent-scheduler#96]
I think it is the same as the callback function, but it can return the progress of image generation **more intuitively**. The only disadvantage may be poor performance optimization.

**Comment by artventuredev** [comment]
So you'd like the callbacks to provide periodic updates during image generation?

**Comment by artventuredev** [comment]
To get the progress of the current task you can use the API `/internal/progress`.

<img width="384" alt="Screenshot 2023-08-02 at 21 34 41" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/df13610a-5ace-4ac5-959d-bbe0622e21be">

Example response:
```json
{
    "active": true,
    "queued": false,
    "completed": false,
    "progress": 0.5,
    "eta": 45.24197196960449,
    "live_preview": "data:image/png;base64,....",
    "id_live_preview": 1,
    "textinfo": null
}
```

**Comment by artventuredev** [comment]
As this is an internal API, I don't have complete knowledge of all the parameters, but here's what I found while debugging:

- The default value for `id_live_preview` seems to be 0 for the initial call.
- For subsequent calls, use the `id_live_preview` value from the previous response.

Regarding `progress`, it represents the task progress, ranging from 0 (0%) to 1 (100%).

Hope this helps!

**Comment by artventuredev** [comment]
I'm sorry but it's SD webui's internal function. There's not much I can do here.

**Comment by artventuredev** [comment]
The progress is already updated after every generation step, but if you query progress too often (faster than needed time to run 1 step), then there will be no change.
